import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
// import Satoshi from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/components/auth-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const satoshi = Satoshi({
//   src: "../../public/fonts/Satoshi-Variable.ttf",
// });

const inter = Inter({});

export const metadata: Metadata = {
  title: {
    default: "ArticleWorm",
    template: "%s | ArticleWorm",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className={`${inter.className}`}>{children}</main>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
